[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fastabx"
version = "0.7.0"
description = "A library for efficient computation of ABX discriminability"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Maxime Poli" },
    { name = "CoML", email = "dev@cognitive-ml.fr" },
]
license = "MIT"
keywords = ["speech", "machine learning"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "numpy>=1.26.4",
    "polars>=1.35.1",
    "torch>=2.9.0",
    "torchdtw>=0.0.1",
    "tqdm>=4.67.1",
]

[project.urls]
homepage = "https://docs.cognitive-ml.fr/fastabx"
documentation = "https://docs.cognitive-ml.fr/fastabx"
repository = "https://github.com/bootphon/fastabx"
changelog = "https://github.com/bootphon/fastabx/releases"

[project.scripts]
fastabx = "fastabx.__main__:main"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "pre-commit>=4.2.0",
    "ruff>=0.13.0",
    "ty>=0.0.1a20",
    "typos>=1.36.2",
]
test = ["hypothesis>=6.135.31", "pytest>=8.4.1"]
doc = [
    "furo>=2024.8.6",
    "matplotlib>=3.10.3",
    "nbconvert>=7.16.6",
    "nbsphinx>=0.9.7",
    "packaging>=25.0",
    "sphinx>=8.1.3",
    "sphinx-copybutton>=0.5.2",
    "sphinx-design>=0.6.1",
]

[tool.ruff]
line-length = 119

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812",  # missing-trailing-comma
    "D105",    # undocumented-magic-method
    "D107",    # undocumented-public-init
    "D203",    # incorrect-blank-line-before-class
    "D213",    # multi-line-summary-second-line
    "PLR0913", # too-many-arguments
]

[tool.ruff.lint.flake8-self]
ignore-names = ["_check"]

[tool.ruff.lint.pylint]
allow-magic-value-types = ["str", "int"]

[tool.ty.rules]
division-by-zero = "warn"
possibly-unresolved-reference = "warn"
unused-ignore-comment = "warn"

[tool.typos.default.extend-words]
IY = "IY"
