name: Push to Gitlab Workflow
permissions: {}

on:
  push:
    branches:
      - main

concurrency:
  group: togitlab-${{ github.ref }}
  cancel-in-progress: false

jobs:
  push:
    name: Push to Gitlab
    runs-on: ubuntu-latest
    environment:
      name: coml-gitlab
    env:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_REPO: gitlab.cognitive-ml.fr/mpoli/fastabx.git
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push
        shell: bash
        run: |
          set -eu
          git config --global user.name "github-actions[bot]"
          git push "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO}" HEAD:main --force
          git push "https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO}" --tags
